import React, { createContext, useContext, useState, ReactNode } from 'react';

export type Language = 'en' | 'ta' | 'te' | 'hi';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
  en: {
    appName: 'HelpHub',
    subtitle: 'An AI-Powered Civic Reporting and Welfare Response System',
    selectLanguage: 'Select Language',
    english: 'English',
    tamil: 'Tamil',
    telugu: 'Telugu',
    hindi: 'Hindi',
    continue: 'Continue',
    user: 'User',
    admin: 'Admin (Organization)',
    volunteer: 'Volunteer',
    reportAnonymously: 'Report Anonymously',
    login: 'Login',
    register: 'Register',
    name: 'Name',
    phone: 'Phone',
    age: 'Age',
    city: 'City',
    email: 'Email',
    password: 'Password',
    confirmPassword: 'Confirm Password',
    username: 'Username',
    dashboard: 'Dashboard',
    reportIssue: 'Report an Issue',
    myReports: 'My Reports',
    emergencyCall: 'Emergency Call',
    help: 'Help',
    uploadPhoto: 'Upload Photo',
    voiceInput: 'Voice Input',
    textInput: 'Describe the issue...',
    submit: 'Submit',
    pending: 'Pending',
    inProgress: 'In Progress',
    resolved: 'Resolved',
    allReports: 'All Reports',
    mapView: 'Map View',
    assignVolunteer: 'Assign to Volunteer',
    sendEmail: 'Send Email',
    manageVolunteers: 'Manage Volunteers',
    statistics: 'Statistics',
    assignedIssues: 'Assigned Issues',
    browseReports: 'Browse Nearby Reports',
    submitUpdate: 'Submit Update',
    activityLog: 'Activity Log',
    profile: 'Profile',
    resume: 'Resume',
    location: 'Location',
    preview: 'Preview',
    filters: 'Filters',
    settings: 'Settings'
  },
  ta: {
    appName: 'ஹெல்ப்ஹப்',
    subtitle: 'AI-சக்தி வாய்ந்த குடிமக்கள் புகார் மற்றும் நலன் பதில் அமைப்பு',
    selectLanguage: 'மொழியைத் தேர்ந்தெடுக்கவும்',
    english: 'ஆங்கிலம்',
    tamil: 'தமிழ்',
    telugu: 'தெலுங்கு',
    hindi: 'இந்தி',
    continue: 'தொடரவும்',
    user: 'பயனர்',
    admin: 'நிர்வாகி (அமைப்பு)',
    volunteer: 'தன்னார்வலர்',
    reportAnonymously: 'அநாமதேயமாக புகார் செய்யுங்கள்',
    login: 'உள்நுழைய',
    register: 'பதிவு செய்ய',
    name: 'பெயர்',
    phone: 'தொலைபேசி',
    age: 'வயது',
    city: 'நகரம்',
    email: 'மின்னஞ்சல்',
    password: 'கடவுச்சொல்',
    confirmPassword: 'கடவுச்சொல்லை உறுதிப்படுத்தவும்',
    username: 'பயனர்பெயர்',
    dashboard: 'டாஷ்போர்டு',
    reportIssue: 'சிக்கலைப் புகாரளிக்கவும்',
    myReports: 'எனது புகார்கள்',
    emergencyCall: 'அவசர அழைப்பு',
    help: 'உதவி',
    uploadPhoto: 'புகைப்படம் பதிவேற்றவும்',
    voiceInput: 'குரல் உள்ளீடு',
    textInput: 'சிக்கலை விவரிக்கவும்...',
    submit: 'சமர்ப்பிக்கவும்',
    pending: 'நிலுவையில்',
    inProgress: 'முன்னேற்றத்தில்',
    resolved: 'தீர்க்கப்பட்டது',
    allReports: 'அனைத்து புகார்கள்',
    mapView: 'வரைபட காட்சி',
    assignVolunteer: 'தன்னார்வலரை நியமிக்கவும்',
    sendEmail: 'மின்னஞ்சல் அனுப்பவும்',
    manageVolunteers: 'தன்னார்வலர்களை நிர்வகிக்கவும்',
    statistics: 'புள்ளிவிவரங்கள்',
    assignedIssues: 'ஒதுக்கப்பட்ட சிக்கல்கள்',
    browseReports: 'அருகிலுள்ள புகார்களைப் பார்க்கவும்',
    submitUpdate: 'புதுப்பிப்பைச் சமர்ப்பிக்கவும்',
    activityLog: 'செயல்பாட்டு பதிவு',
    profile: 'சுயவிவரம்',
    resume: 'விண்ணப்பம்',
    location: 'இடம்',
    preview: 'முன்னோட்டம்',
    filters: 'வடிகட்டிகள்',
    settings: 'அமைப்புகள்'
  },
  te: {
    appName: 'హెల్ప్‌హబ్',
    subtitle: 'AI-శక్తితో కూడిన పౌర రిపోర్టింగ్ మరియు సంక్షేమ ప్రతిస్పందన వ్యవస్థ',
    selectLanguage: 'భాషను ఎంచుకోండి',
    english: 'ఇంగ్లీష్',
    tamil: 'తమిళం',
    telugu: 'తెలుగు',
    hindi: 'హిందీ',
    continue: 'కొనసాగించు',
    user: 'వినియోగదారు',
    admin: 'నిర్వాహకుడు (సంస్థ)',
    volunteer: 'స్వచ్ఛంద సేవకుడు',
    reportAnonymously: 'అనామకంగా రిపోర్ట్ చేయండి',
    login: 'లాగిన్',
    register: 'నమోదు',
    name: 'పేరు',
    phone: 'ఫోన్',
    age: 'వయస్సు',
    city: 'నగరం',
    email: 'ఇమెయిల్',
    password: 'పాస్‌వర్డ్',
    confirmPassword: 'పాస్‌వర్డ్‌ను నిర్ధారించండి',
    username: 'వినియోగదారు పేరు',
    dashboard: 'డాష్‌బోర్డ్',
    reportIssue: 'సమస్యను రిపోర్ట్ చేయండి',
    myReports: 'నా రిపోర్ట్‌లు',
    emergencyCall: 'అత్యవసర కాల్',
    help: 'సహాయం',
    uploadPhoto: 'ఫోటో అప్‌లోడ్ చేయండి',
    voiceInput: 'వాయిస్ ఇన్‌పుట్',
    textInput: 'సమస్యను వివరించండి...',
    submit: 'సమర్పించు',
    pending: 'పెండింగ్',
    inProgress: 'ప్రగతిలో',
    resolved: 'పరిష్కరించబడింది',
    allReports: 'అన్ని రిపోర్ట్‌లు',
    mapView: 'మ్యాప్ వ్యూ',
    assignVolunteer: 'స్వచ్ఛంద సేవకుడికి కేటాయించు',
    sendEmail: 'ఇమెయిల్ పంపు',
    manageVolunteers: 'స్వచ్ఛంద సేవకులను నిర్వహించు',
    statistics: 'గణాంకాలు',
    assignedIssues: 'కేటాయించిన సమస్యలు',
    browseReports: 'సమీపంలోని రిపోర్ట్‌లను చూడండి',
    submitUpdate: 'అప్‌డేట్ సమర్పించు',
    activityLog: 'కార్యకలాప లాగ్',
    profile: 'ప్రొఫైల్',
    resume: 'రెజ్యూమ్',
    location: 'స్థానం',
    preview: 'ప్రివ్యూ',
    filters: 'ఫిల్టర్‌లు',
    settings: 'సెట్టింగ్‌లు'
  },
  hi: {
    appName: 'हेल्पहब',
    subtitle: 'AI-संचालित नागरिक रिपोर्टिंग और कल्याण प्रतिक्रिया प्रणाली',
    selectLanguage: 'भाषा चुनें',
    english: 'अंग्रेजी',
    tamil: 'तमिल',
    telugu: 'तेलुगु',
    hindi: 'हिंदी',
    continue: 'जारी रखें',
    user: 'उपयोगकर्ता',
    admin: 'प्रशासक (संगठन)',
    volunteer: 'स्वयंसेवक',
    reportAnonymously: 'गुमनाम रूप से रिपोर्ट करें',
    login: 'लॉगिन',
    register: 'पंजीकरण',
    name: 'नाम',
    phone: 'फोन',
    age: 'उम्र',
    city: 'शहर',
    email: 'ईमेल',
    password: 'पासवर्ड',
    confirmPassword: 'पासवर्ड की पुष्टि करें',
    username: 'उपयोगकर्ता नाम',
    dashboard: 'डैशबोर्ड',
    reportIssue: 'समस्या की रिपोर्ट करें',
    myReports: 'मेरी रिपोर्ट्स',
    emergencyCall: 'आपातकालीन कॉल',
    help: 'सहायता',
    uploadPhoto: 'फोटो अपलोड करें',
    voiceInput: 'वॉयस इनपुट',
    textInput: 'समस्या का वर्णन करें...',
    submit: 'जमा करें',
    pending: 'लंबित',
    inProgress: 'प्रगति में',
    resolved: 'हल हो गया',
    allReports: 'सभी रिपोर्ट्स',
    mapView: 'मैप व्यू',
    assignVolunteer: 'स्वयंसेवक को असाइन करें',
    sendEmail: 'ईमेल भेजें',
    manageVolunteers: 'स्वयंसेवकों का प्रबंधन',
    statistics: 'आंकड़े',
    assignedIssues: 'असाइन किए गए मुद्दे',
    browseReports: 'आस-पास की रिपोर्ट्स देखें',
    submitUpdate: 'अपडेट जमा करें',
    activityLog: 'गतिविधि लॉग',
    profile: 'प्रोफाइल',
    resume: 'रिज्यूमे',
    location: 'स्थान',
    preview: 'पूर्वावलोकन',
    filters: 'फिल्टर',
    settings: 'सेटिंग्स'
  }
};

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('en');

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations['en']] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};